Sample Size Simulation Results
========================================================

author: John Swenson
date: 4/1/2019
autosize: true

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory
```{r, echo=FALSE}
#Set working directory to results folder
setwd("~/R/R_working_dir/CKMR/CKMR_simulations/Results/Non_lethal_null_sim/")
list.files()
```

Import and analyze results
```{r, echo=FALSE}
f_truth <- 1000
m_truth <- 1500
non_sim <- read.csv("Lemon_CKMR_loop_nonlethalsim_500_samples.csv")
head(non_sim)

#Check for NAs
length(which(is.na(non_sim[,1])==TRUE))

#Calculate means
m_mean <- mean(non_sim$Nm)
m_SE <- mean(non_sim$NmSE)
f_mean <- mean(non_sim$Nf)
f_SE <- mean(non_sim$NfSE)

#Reformat dataframes for ggplot
F_truth <- 1000
M_truth <- 1500

m_df <- non_sim[,3:6]
m_df$Sex <- "M"
m_df$rel_bias <- ((non_sim$Nm - M_truth)/M_truth)*100
m_rel_bias_mean <- round(mean(m_df$rel_bias),1)

f_df <- non_sim[,c(1:2, 5:6)]
f_df$Sex <- "F"
f_df$rel_bias <- ((non_sim$Nf - F_truth)/F_truth)*100
f_rel_bias_mean <- round(mean(f_df$rel_bias),1)

colnames(f_df)[1:2] = colnames(m_df)[1:2] <-  c("Abund","SE")
head(f_df)
head(m_df)

non_sim_plot <- rbind(m_df, f_df)
```

Visualize results
```{r, echo=FALSE}
library(ggplot2)
head(non_sim_plot)
#Box plot of relative bias of abundance estimate
ggplot(data=non_sim_plot, aes(x=Sex, y=rel_bias)) +
  geom_boxplot() +
  geom_abline(intercept = 0, slope = 0, color="dark red") +
  ggtitle("CKMR Non-lethal Null Model Simulations (500 samples)") +
  xlab("Sex") +
  ylab("Relative bias") +
  geom_label(aes(label=paste0("Relative bias: ",m_rel_bias_mean), x=2, y=50), fill="lightskyblue1", colour="darkslategray", fontface="bold", show.legend=NA) +
  geom_label(aes(label=paste0("Relative bias: ",f_rel_bias_mean), x=1, y=50), fill="indianred1", colour="darkred", fontface="bold", show.legend=NA)  

####Visualize relative bias by POPs detected
ggplot(data=non_sim_plot)
```