---
title: "Model_analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Null model 1
```{r echo=FALSE}
#Rows are individual samples; columns are iterations - use these to find age distributions of samples
Samps_30 <- read.csv("~/R/R_working_dir/CKMR/Results/HS_constant_abundance/HS_sampled_ages_small_pop_30_samps_06.04.2020.csv", header=TRUE)
Samps_60 <- read.csv("~/R/R_working_dir/CKMR/Results/HS_constant_abundance/HS_sampled_ages_small_pop_60_samps_06.04.2020.csv", header=TRUE)
Samps_90 <- read.csv("~/R/R_working_dir/CKMR/Results/HS_constant_abundance/HS_sampled_ages_small_pop_90_samps_06.04.2020.csv", header=TRUE)
Samps_120 <- read.csv("~/R/R_working_dir/CKMR/Results/HS_constant_abundance/HS_sampled_ages_small_pop_120_samps_06.04.2020.csv", header=TRUE)
Samps_150 <- read.csv("~/R/R_working_dir/CKMR/Results/HS_constant_abundance/HS_sampled_ages_small_pop_150_samps_06.04.2020.csv", header=TRUE)

#Assumes dataframe HS has been populated from HS_viz script
head(HS)

#Mean relative bias by sample size and sex
HS %>% group_by(Total_samples, Sex) %>% 
  summarize(Mean_rel_bias = mean(Relative_bias))

#Mean parents detected by sample size and sex
HS %>% group_by(Total_samples, Sex) %>% 
  drop_na() %>% 
  summarize(Mean_rents_detected = mean(Parents_detected))

#Find insane values
#Subset for highly biased estimates
Hi_bias_pos <- HS[HS$Relative_bias > 50,]
head(Hi_bias_pos)

Hi_bias_neg <- HS[HS$Relative_bias < -30,]
View(Hi_bias_neg)

Hi_bias_neg %>% 
  group_by(Total_samples) %>% 
  drop_na() %>% 
  summarize(mean(Parents_detected))

Hi_bias_pos %>% 
  group_by(Total_samples) %>% 
  drop_na() %>% 
  summarize(mean(Parents_detected))

Lo_bias <- HS[HS$Relative_bias < 20 & HS$Relative_bias > -20,]
  
Lo_bias %>% 
  group_by(Total_samples) %>% 
  drop_na() %>% 
  summarize(mean(Parents_detected))

#Look specifically for insane values when 60 samples were taken (there were SUPER biased estimates)
#Females for each sample size are rows 1-500, males are rows 501-1000
HS_60 <- HS[which(HS$Total_samples==60),]
which(HS_60$Relative_bias > 500) #The super biased estimates are rows 539 and 567, which correspond to iterations 39 and 67 for males (and the respective rows in the Sampes_60 dataframe).
HS_60[c(539, 567),] #Get biased rows from HS_60 dataframe - note just one parent detected and cannot calculate SE

table(Samps_60[,39]) #Get sample ages from those runs
table(Samps_60[,67]) #Get sample ages from those runs
table(Samps_60[,2]) #Get sample ages from unbiased run
#Age distribution doesn't appear to be weird; seems like it's more likely related to the number of kin pairs found
```