---
title: "Data_analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("pconn/HierarchicalGOF/HierarchicalGOF")
#install.packages("ggmcmc")
```

```{r read in files}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(coda)
library(runjags)
library(ggmcmc)
library(viridis)

rm(list=ls())
today <- format(Sys.Date(), "%d%b%Y")
purpose.combo <- "comparison.1" #What am I comparing right now? This will be used to name output files

#----------------Read in files ------------------------------
#------------- MCMC parameters ----------------#
ni <- 40000 # number of post-burn-in samples per chain
nb <- 50000 # number of burn-in samples
nt <- 20     # thinning rate
nc <- 2      # number of chains
MCMC.settings <- paste0("thin", nt, "_draw", ni, "_burn", nb)

#------------- Simulation parameters and labels  ----------------#
date.of.simulation1 <- "19Apr2022"
purpose1 <- "HS.PO_target.age_all.samples"
purpose1.lab <- "HS + PO model"
model.type1 <- "HS.PO"

date.of.simulation2 <- "19Apr2022"
purpose2 <- "HS.only_target.age_all.samples"
purpose2.lab <- "HS only model"
model.type2 <- "HS.only"

date.of.simulation3 <- "19Apr2022"
purpose3 <- "PO.only_target.age_all.samples"
purpose3.lab <- "PO only model"
model.type3 <- "PO.only"

date.of.simulation4 <- "11Apr2022"
purpose4 <- "HS.PO_refined.samples_downsample"
purpose4.lab <- "targeted sampling | downsample"
model.type4 <- "HS.PO"

seeds <- "Seeds2022.04.15"
sim.samples.1 = samples1.lab <- "240.samples"
sim.samples.2 = samples2.lab <- "480.samples"
sim.samples.3 = samples3.lab <- "720.samples"
sim.samples.4 = samples4.lab <- "960.samples"
sim.samples.all <- c(240, 480, 720, 960)

MCMC_location <- "G://My Drive/Personal_Drive/R/CKMR/Objective.1_model.construction/Model.output/"
results_location <- "G://My Drive/Personal_Drive/R/CKMR/Objective.1_model.construction/Model.results/"
results_plots_location <- "G://My Drive/Personal_Drive/R/CKMR/Objective.1_model.construction/Model.results/figures/"
results_prefix <- "CKMR_results"
MCMC_prefix <- "CKMR_modelout"
parents_prefix <- "parents_breakdown/CKMR_parents.breakdown"
sample.prefix <- "sample_info/CKMR_sample.info"
survival.prefix <- "survival/CKMR_survival"
pop.size.prefix <- "pop_size/CKMR_pop.size"
mom.comps.prefix <- "comparisons/mom.comps"
dad.comps.prefix <- "comparisons/dad.comps"


#Set results to NULL and the script will run regardless of how many actual results are being compared
results.1 = results.2 = results.3 = results.4 <- NULL

results.1 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1, ".csv")) %>% 
  mutate(model_type = model.type1, 
         purpose.lab = purpose1.lab)

results.2 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2, ".csv")) %>% 
  mutate(model_type = model.type2,
         purpose.lab = purpose2.lab)

results.3 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3, ".csv")) %>% 
  mutate(model_type = model.type3,
         purpose.lab = purpose3.lab)

results.4 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4, ".csv")) %>% 
    mutate(model_type = model.type4,
           purpose.lab = purpose4.lab)


#------------------------------- MCMC output -----------------------------------#
#date.of.simulation <- "07Apr2022"
#Trial 1
s1.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose1))

s1.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose1))

s1.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose1))

s1.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose1))

#Trial 2
s2.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose2))

s2.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose2))

s2.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose2))

s2.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose2))

#Trial 3
#date.of.simulation <- "05Apr2022"
s3.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose3))

s3.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose3))

s3.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose3))

s3.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose3))

#Trial 4
 s4.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose4))

 s4.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose4))

 s4.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose4))
 
  s4.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose4))

#------------------------------- Population size details -----------------------------------#
#date.of.simulation <- "07Apr2022"
pop.size.1 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1))

pop.size.2 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2))

pop.size.3 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3))

pop.size.4 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4))

#------------------------------ Pairwise comparison matrices -------------------------------#
#Mom
mom.comps.1 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1))

mom.comps.2 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2))

mom.comps.3 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3))

mom.comps.4 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4))

#Dad
dad.comps.1 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1))

dad.comps.2 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2))

dad.comps.3 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3))

dad.comps.4 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4))

```

```{r Quick analysis of results}
####------------------------------- Quick analysis of results -----------------------------------####

results.all <- results.1 %>% 
  bind_rows(results.2, results.3, results.4) %>% 
  mutate(relative_bias = round(((Q50 - truth)/truth)*100,1)) %>%
  mutate(in_interval = ifelse(HPD2.5 < truth & truth < HPD97.5, "Y", "N")) %>% 
  mutate(cv = (sd/mean)*100) %>% 
  mutate(samples.lab = paste0(total_samples, ".samples"))
results.all$samples.lab <- factor(results.all$samples.lab, levels = c(samples1.lab, samples2.lab, samples3.lab, samples4.lab))

jags_params <- c("Nf", "Nm", "surv", "lam") #Specify parameters

head(results.all)

results.all$purpose.lab <- factor(results.all$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab))

#View instances where the model failed to converge
results.all %>% dplyr::filter(Rhat > 1.01) %>% View()
 
 #-----------Median Relative bias by sample size-------------------------#
results.all %>% group_by(total_samples, parameter, purpose.lab) %>% 
#  dplyr::filter(model_type == "HS.PO") %>%
  dplyr::summarize(median = median(relative_bias), n = n()) %>% 
  arrange(desc(median)) %>% 
  View()

# results2 %>% dplyr::filter(parameter == "lam") %>% 
#   ggplot(aes(relative_bias, colour = which.dup, fill = which.dup)) +
#   geom_density(alpha = 0.5)
# 
# 
# results2 %>%  mutate(cv = (sd/mean)*100) %>% 
#   group_by(parameter, which.dup) %>% 
#   dplyr::summarize(mean.cv = mean(cv), mean.relative.bias = mean(relative_bias)) %>%
# #  dplyr::filter(parameter == "Nf" | parameter == "Nm") %>% 
#   arrange(mean.cv) %>% 
#   write_csv(file = paste0(results_location, "Mean_bias_and_precision_", date.of.simulation, "_", purpose, ".csv"))


#------------------------------- Within HPDI? -----------------------------------#
results.all %>% group_by(purpose.lab, total_samples, parameter) %>% 
  dplyr::summarize(percent_in_interval = sum(in_interval == "Y")/n() * 100) %>% 
#  filter(parameter != "lam") %>% 
  arrange(desc(percent_in_interval)) %>% 
  View()

#------------------------------- CV -----------------------------------#
results.all %>% group_by(model_type, purpose.lab, total_samples, parameter) %>% 
  dplyr::summarize(mean.cv = mean(cv), 
                   median.bias = median(relative_bias),
                   percent_in_interval = sum(in_interval == "Y")/n() * 100) %>%
#  dplyr::filter(parameter == "Nf" | parameter == "Nm") %>% 
  arrange(mean.cv) %>% 
  write_csv(file = paste0(results_location, "Mean_bias_and_precision_", today, "_", purpose.combo, ".csv"))
```

```{r Calcualte HPDI intervals}
####------------------------------- Calculate different HPDI intervals-------------------------------#### 
#How many estimates fall in different HPD intervals?
#Calculate HPD interval for each iteration
intervals <- c(seq(from = 0.95, to = 0.05, by = -0.05)) #Specify HPDI intervals to calculate
iterations = 200

#Assumes four "purposes" are being compared
#Initialize dataframes for loop below
HPD.240.1 <- NULL
HPD.480.1 <- NULL
HPD.720.1 <- NULL
HPD.960.1 <- NULL
HPD.240.2 <- NULL
HPD.480.2 <- NULL
HPD.720.2 <- NULL
HPD.960.2 <- NULL
HPD.240.3 <- NULL
HPD.480.3 <- NULL
HPD.720.3 <- NULL
HPD.960.3 <- NULL
HPD.240.4 <- NULL
HPD.480.4 <- NULL
HPD.720.4 <- NULL
HPD.960.4 <- NULL


#Check lists for null and remove
#length(s3.4[-which(sapply(s3.1, is.null))])
#s3.1 <- s3.1[-which(sapply(s3.1, is.null))]

#Assumes all scenarios have the same number of saved iterations; if not, then can just run a separate for loop
for(i in 1:length(s1.1)){ #Loop over all the posterior samples from each iteration; length should be same as number of iterations
  for(j in 1:length(intervals)){ #Loop over the different intervals for calculating HPDI
    
    #---------------------------Purpose 1--------------------------------#
    #240 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.240.1 <- combine.mcmc(s1.1[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.240.1 <- post.HPD.240.1[row.names(post.HPD.240.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.240.1 <- rbind(HPD.240.1, post.HPD.240.1)
    
    #480 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.480.1 <- combine.mcmc(s1.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.480.1 <- post.HPD.480.1[row.names(post.HPD.480.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.480.1 <- rbind(HPD.480.1, post.HPD.480.1)
    
     #720 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.720.1 <- combine.mcmc(s1.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.720.1 <- post.HPD.720.1[row.names(post.HPD.720.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.720.1 <- rbind(HPD.720.1, post.HPD.720.1)

    #960 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.960.1 <- combine.mcmc(s1.3[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.960.1 <- post.HPD.960.1[row.names(post.HPD.960.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.960.1 <- rbind(HPD.960.1, post.HPD.960.1)
    
    
    #---------------------------Purpose 2--------------------------------#    
    #240 samples
    #Calcualte HPD interval for iteration i and interval j
    
    post.HPD.240.2 <- combine.mcmc(s2.1[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.240.2 <- post.HPD.240.2[row.names(post.HPD.240.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.240.2 <- rbind(HPD.240.2, post.HPD.240.2)
    
    #480 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.480.2 <- combine.mcmc(s2.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.480.2 <- post.HPD.480.2[row.names(post.HPD.480.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.480.2 <- rbind(HPD.480.2, post.HPD.480.2)
    
        #720 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.720.2 <- combine.mcmc(s2.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.720.2 <- post.HPD.720.2[row.names(post.HPD.720.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.720.2 <- rbind(HPD.720.2, post.HPD.720.2)
    
    #960 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.960.2 <- combine.mcmc(s2.3[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.960.2 <- post.HPD.960.2[row.names(post.HPD.960.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.960.2 <- rbind(HPD.960.2, post.HPD.960.2)
  }    
     print(paste0("Finished with iteration ", i))
  }

  
for(i in 1:length(s3.1)){ #Loop over all the posterior samples from each iteration; length should be same as number of iterations
  for(j in 1:length(intervals)){ #Loop over the different intervals for calculating HPDI

   # #---------------------------Purpose 3--------------------------------#
    #240 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.240.3 <- combine.mcmc(s3.1[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.240.3 <- post.HPD.240.3[row.names(post.HPD.240.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.240.3 <- rbind(HPD.240.3, post.HPD.240.3)
    
  }
  print(paste0("Finished with iteration ", i))
  }

for(i in 1:length(s3.2)){ #Loop over all the posterior samples from each iteration; length should be same as number of iterations
  for(j in 1:length(intervals)){ #Loop over the different intervals for calculating HPDI
    #480 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.480.3 <- combine.mcmc(s3.2[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.480.3 <- post.HPD.480.3[row.names(post.HPD.480.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.480.3 <- rbind(HPD.480.3, post.HPD.480.3)
    
        #720 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.720.3 <- combine.mcmc(s3.2[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.720.3 <- post.HPD.720.3[row.names(post.HPD.720.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.720.3 <- rbind(HPD.720.3, post.HPD.720.3)

    #960 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.960.3 <- combine.mcmc(s3.3[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.960.3 <- post.HPD.960.3[row.names(post.HPD.960.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.960.3 <- rbind(HPD.960.3, post.HPD.960.3)

    # #---------------------------Purpose 4--------------------------------#
    #240 samples
    #Calcualte HPD interval for iteration i and interval j
    # post.HPD.240.4 <- combine.mcmc(s4.1[[i]]) %>%
    #   HPDinterval(prob = intervals[j]) %>%
    #   data.frame() %>%
    #   mutate(interval = intervals[j], iteration = i)
    # 
    # post.HPD.240.4 <- post.HPD.240.4[row.names(post.HPD.240.4) %in% jags_params,] %>% #Remove deviance
    #   rownames_to_column(var = "parameter")
    # 
    # HPD.240.4 <- rbind(HPD.240.4, post.HPD.240.4)
    # 
    # #480 samples
    # #Calcualte HPD interval for iteration i and interval j
    # post.HPD.480.4 <- combine.mcmc(s4.2[[i]]) %>%
    #   HPDinterval(prob = intervals[j]) %>%
    #   data.frame() %>%
    #   mutate(interval = intervals[j], iteration = i)
    # 
    # post.HPD.480.4 <- post.HPD.480.4[row.names(post.HPD.480.4) %in% jags_params,] %>% #Remove deviance
    #   rownames_to_column(var = "parameter")
    # 
    # HPD.480.4 <- rbind(HPD.480.4, post.HPD.480.4)
    # 
    #     #720 samples
    # #Calcualte HPD interval for iteration i and interval j
    # post.HPD.720.4 <- combine.mcmc(s4.2[[i]]) %>%
    #   HPDinterval(prob = intervals[j]) %>%
    #   data.frame() %>%
    #   mutate(interval = intervals[j], iteration = i)
    # 
    # post.HPD.720.4 <- post.HPD.720.4[row.names(post.HPD.720.4) %in% jags_params,] %>% #Remove deviance
    #   rownames_to_column(var = "parameter")
    # 
    # HPD.720.4 <- rbind(HPD.720.4, post.HPD.720.4)
    # 
    # #960 samples
    # #Calcualte HPD interval for iteration i and interval j
    # post.HPD.960.4 <- combine.mcmc(s4.3[[i]]) %>%
    #   HPDinterval(prob = intervals[j]) %>%
    #   data.frame() %>%
    #   mutate(interval = intervals[j], iteration = i)
    # 
    # post.HPD.960.4 <- post.HPD.960.4[row.names(post.HPD.960.4) %in% jags_params,] %>% #Remove deviance
    #   rownames_to_column(var = "parameter")
    # 
    # HPD.960.4 <- rbind(HPD.960.4, post.HPD.960.4)
    
  }
  print(paste0("Finished with iteration ", i))
  }
```

```{r Create dataframes for HPDI plots}
####------------------------------- Create dataframes for HPDI plotting------------------------------#### 

#---------------------------Purpose 1 --------------------------------#    
#Separate out by sample size
HPD.240.1.4viz <- results.1 %>% filter(total_samples == 240) %>% 
  right_join(HPD.240.1, by = c("parameter", "iteration"))

HPD.480.1.4viz <- results.1 %>% filter(total_samples == 480) %>% 
  right_join(HPD.480.1, by = c("parameter", "iteration"))

HPD.720.1.4viz <- results.1 %>% filter(total_samples == 720) %>% 
  right_join(HPD.720.1, by = c("parameter", "iteration"))

HPD.960.1.4viz <- results.1 %>% filter(total_samples == 960) %>% 
  right_join(HPD.960.1, by = c("parameter", "iteration"))


#Calculate percent estimates in each interval
HPD.240.1.summary <- HPD.240.1.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.240.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.480.1.summary <- HPD.480.1.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.480.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.720.1.summary <- HPD.720.1.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.720.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD960.1.summary <- HPD.960.1.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.960.samples = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes    
HPD.1.summary_all <- HPD.240.1.summary %>% inner_join(HPD.480.1.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD.720.1.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD960.1.summary, by = c("parameter", "interval")) %>% 
  mutate(interval.scale = interval*100)

HPD.1.summary.tidy <- HPD.1.summary_all %>% 
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "samples",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
    ) %>% 
  mutate(model_type = model.type1,
         purpose.lab = purpose1.lab)

#Save
#write_csv(HPD.1.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation1, "_", purpose1, ".csv"))


#---------------------------Purpose 2 --------------------------------#    
#Separate out by sample size
HPD.240.2.4viz <- results.2 %>% filter(total_samples == 240) %>% 
  right_join(HPD.240.2, by = c("parameter", "iteration"))

HPD.480.2.4viz <- results.2 %>% filter(total_samples == 480) %>% 
  right_join(HPD.480.2, by = c("parameter", "iteration"))

HPD.720.2.4viz <- results.2 %>% filter(total_samples == 720) %>% 
  right_join(HPD.720.2, by = c("parameter", "iteration"))

HPD.960.2.4viz <- results.2 %>% filter(total_samples == 960) %>% 
  right_join(HPD.960.2, by = c("parameter", "iteration"))


#Calculate percent estimates in each interval
HPD.240.2.summary <- HPD.240.2.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.240.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.480.2.summary <- HPD.480.2.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.480.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.720.2.summary <- HPD.720.2.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.720.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD960.2.summary <- HPD.960.2.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.960.samples = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes
HPD.2.summary_all <- HPD.240.2.summary %>% inner_join(HPD.480.2.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD.720.2.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD960.2.summary, by = c("parameter", "interval")) %>% 
  mutate(interval.scale = interval*100)

HPD.2.summary.tidy <- HPD.2.summary_all %>% 
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "samples",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
  ) %>% 
  mutate(model_type = model.type2,
                  purpose.lab = purpose2.lab)

#Save
#write_csv(HPD.2.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation2, "_", purpose2, ".csv"))


#---------------------------Purpose 3 --------------------------------# 
#Separate out by sample size
HPD.240.3.4viz <- results.3 %>% filter(total_samples == 240) %>% 
  right_join(HPD.240.3, by = c("parameter", "iteration"))

HPD.480.3.4viz <- results.3 %>% filter(total_samples == 480) %>% 
  right_join(HPD.480.3, by = c("parameter", "iteration"))

HPD.720.3.4viz <- results.3 %>% filter(total_samples == 720) %>% 
  right_join(HPD.720.3, by = c("parameter", "iteration"))

HPD.960.3.4viz <- results.3 %>% filter(total_samples == 960) %>% 
  right_join(HPD.960.3, by = c("parameter", "iteration"))


#Calculate percent estimates in each interval
HPD.240.3.summary <- HPD.240.3.4viz %>% group_by(parameter, interval) %>% 
  drop_na() %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.240.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.480.3.summary <- HPD.480.3.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.480.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.720.3.summary <- HPD.720.3.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.720.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD960.3.summary <- HPD.960.3.4viz %>% group_by(parameter, interval) %>% 
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>% 
  dplyr::summarize(percent_in_interval.960.samples = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes
HPD.3.summary_all <- HPD.240.3.summary %>% inner_join(HPD.480.3.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD.720.3.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD960.3.summary, by = c("parameter", "interval")) %>% 
  mutate(interval.scale = interval*100)

HPD.3.summary.tidy <- HPD.3.summary_all %>% 
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "samples",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
  ) %>% 
  mutate(model_type = model.type3,
         purpose.lab = purpose3.lab)

#Save
#write_csv(HPD.3.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation3, "_", purpose3, ".csv"))


#---------------------------Purpose 4 --------------------------------# 
#Separate out by sample size
HPD.240.4.4viz <- results.4 %>% filter(total_samples == 240) %>%
  right_join(HPD.240.4, by = c("parameter", "iteration"))

HPD.480.4.4viz <- results.4 %>% filter(total_samples == 480) %>%
  right_join(HPD.480.4, by = c("parameter", "iteration"))

HPD.720.4.4viz <- results.4 %>% filter(total_samples == 720) %>%
  right_join(HPD.720.4, by = c("parameter", "iteration"))

HPD.960.4.4viz <- results.4 %>% filter(total_samples == 960) %>%
  right_join(HPD.960.4, by = c("parameter", "iteration"))


#Calculate percent estimates in each interval
HPD.240.4.summary <- HPD.240.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>%
  dplyr::summarize(percent_in_interval.240.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.480.4.summary <- HPD.480.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>%
  dplyr::summarize(percent_in_interval.480.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD.720.4.summary <- HPD.720.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>%
  dplyr::summarize(percent_in_interval.720.samples = sum(in_HPD_interval == "Y")/n() * 100)

HPD960.4.summary <- HPD.960.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(lower < truth & truth < upper, "Y", "N")) %>%
  dplyr::summarize(percent_in_interval.960.samples = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes
HPD.4.summary_all <- HPD.240.4.summary %>% inner_join(HPD.480.4.summary, by = c("parameter", "interval")) %>%
  inner_join(HPD.720.4.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD960.4.summary, by = c("parameter", "interval")) %>%
  mutate(interval.scale = interval*100)

HPD.4.summary.tidy <- HPD.4.summary_all %>%
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "samples",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
  ) %>%
  mutate(model_type = model.type4,
         purpose.lab = purpose4.lab)

#Save
#write_csv(HPD.4.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation, "_", purpose4, ".csv"))



#---------------Create dataframes to plot by sample size--------#
#Set eveyrthing to Null so the below scripts will run
HPD.240.1.4viz = HPD.480.1.4viz = HPD.720.1.4viz = HPD.960.1.4viz = HPD.240.2.4viz = HPD.480.2.4viz = HPD.720.2.4viz = HPD.960.2.4viz = HPD.240.3.4viz = HPD.480.3.4viz = HPD.720.3.4viz = HPD.960.3.4viz = HPD.240.4.4viz = HPD.480.4.4viz = HPD.720.4.4viz = HPD.960.4.4viz <- NULL

HPD.240.1.4viz <- HPD.1.summary.tidy %>% filter(samples == "240.samples")
HPD.480.1.4viz <- HPD.1.summary.tidy %>% filter(samples == "480.samples")
HPD.720.1.4viz <- HPD.1.summary.tidy %>% filter(samples == "720.samples")
HPD.960.1.4viz <- HPD.1.summary.tidy %>% filter(samples == "960.samples")

HPD.240.2.4viz <- HPD.2.summary.tidy %>% filter(samples == "240.samples")
HPD.480.2.4viz <- HPD.2.summary.tidy %>% filter(samples == "480.samples")
HPD.720.2.4viz <- HPD.2.summary.tidy %>% filter(samples == "720.samples")
HPD.960.2.4viz <- HPD.2.summary.tidy %>% filter(samples == "960.samples")

HPD.240.3.4viz <- HPD.3.summary.tidy %>% filter(samples == "240.samples")
HPD.480.3.4viz <- HPD.3.summary.tidy %>% filter(samples == "480.samples")
HPD.720.3.4viz <- HPD.3.summary.tidy %>% filter(samples == "720.samples")
HPD.960.3.4viz <- HPD.3.summary.tidy %>% filter(samples == "960.samples")

HPD.240.4.4viz <- HPD.4.summary.tidy %>% filter(samples == "240.samples")
HPD.480.4.4viz <- HPD.4.summary.tidy %>% filter(samples == "480.samples")
HPD.720.4.4viz <- HPD.4.summary.tidy %>% filter(samples == "720.samples")
HPD.960.4.4viz <- HPD.4.summary.tidy %>% filter(samples == "960.samples")


#Combine above dataframes, and re-order purpose as factors
all.240.4viz <- HPD.240.1.4viz %>% bind_rows(HPD.240.2.4viz, HPD.240.3.4viz, HPD.240.4.4viz) 
all.240.4viz$purpose.lab <- factor(all.240.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

all.480.4viz <- HPD.480.1.4viz %>% bind_rows(HPD.480.2.4viz, HPD.480.3.4viz, HPD.480.4.4viz) 
all.480.4viz$purpose.lab <- factor(all.480.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

all.720.4viz <- HPD.720.1.4viz %>% bind_rows(HPD.720.2.4viz, HPD.720.3.4viz, HPD.720.4.4viz) 
all.720.4viz$purpose.lab <- factor(all.720.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

all.960.4viz <- HPD.960.1.4viz %>% bind_rows(HPD.960.2.4viz, HPD.960.3.4viz, HPD.960.4.4viz)

all.960.4viz$purpose.lab <- factor(all.960.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

#For when we need everything together
all.4viz <- HPD.1.summary.tidy %>% bind_rows(HPD.2.summary.tidy, HPD.3.summary.tidy)
all.4viz$purpose.lab <- factor(all.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))
```

```{r Figure 1}
#myColors <- brewer.pal(3, "Dark2")
#names(myColors) <- levels(results.all$purpose.lab)
#custom_colors <- scale_colour_viridis(values = myColors, discrete = TRUE)

#-----------------------Make figures-----------------------------
#-----------------HPDI plot--------------------#
(p.Nf <- all.4viz %>% dplyr::filter(parameter == "Nf") %>% 
  ggplot(aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("Nf") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~samples))



p.Nm <- all.4viz %>% dplyr::filter(parameter == "Nm") %>% 
  ggplot(aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("Nm") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~samples)


p.surv <- all.4viz %>% dplyr::filter(parameter == "surv") %>% 
  ggplot(aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("Survival") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~samples)

#May want to add this: purpose.lab != purpose3.lab to the first line to filter out PO from lambda
p.lam <- all.4viz %>% dplyr::filter(parameter == "lam") %>% 
  ggplot(aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("Lambda") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~samples)


HPDI.plots <- ggarrange(p.Nf, p.Nm, p.surv, p.lam, common.legend = TRUE, ncol = 2, nrow = 2, legend = "bottom")
annotate_figure(p = HPDI.plots, fig.lab = "C)", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")

#Density plots
(p2.Nf <- results.all %>% dplyr::filter(parameter == "Nf") %>% 
  ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
  ggtitle("Nf") + 
  labs(x = "Relative bias of posterior median") +
  geom_vline(xintercept=c(0), linetype="dotted") +
    theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Set1") +
  xlim(-50, 50) + 
  facet_wrap(~samples.lab))


p2.Nm <- results.all %>% dplyr::filter(parameter == "Nm") %>% 
  ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
  ggtitle("Nm") + 
  labs(x = "Relative bias of posterior median") +
  geom_vline(xintercept=c(0), linetype="dotted") +
    theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Set1") +
  xlim(-50, 50) + 
  facet_wrap(~samples.lab)

p2.surv <- results.all %>% dplyr::filter(parameter == "surv") %>% 
  ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
  ggtitle("Survival") + 
  labs(x = "Relative bias of posterior median") +
  geom_vline(xintercept=c(0), linetype="dotted") +
    theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Set1") +
  xlim(-50, 50) + 
  facet_wrap(~samples.lab)

(p2.lam <- results.all %>% dplyr::filter(parameter == "lam", purpose.lab != purpose3.lab) %>% 
  ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
  ggtitle("Lambda") + 
  labs(x = "Relative bias of posterior median") +
  geom_vline(xintercept=c(0), linetype="dotted") +
    theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Set1") +
  xlim(-10, 10) + 
  facet_wrap(~samples.lab))

RelBias.Density.Plots <- ggarrange(p2.Nf, p2.Nm, p2.surv, p2.lam, common.legend = TRUE, ncol = 2, nrow = 2, legend = "bottom")
annotate_figure(p = RelBias.Density.Plots, fig.lab = "D)", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")

#To look at colors to make them match
#library(scales)
#show_col(hue_pal()(4))
```


PIck up here on 4/21/2022
```{r Figure 2}
#-----------------------Make figures-----------------------------
#-----------------HPDI plot--------------------#
#Nm & surv - 240 samples
#Random (non-targeted) sampling: all comparisons and downsample
p1.240.df <- all.240.4viz %>% filter(parameter == "Nm" | parameter == "surv" | parameter == "Nf") %>% 
  dplyr::filter(purpose == purpose1.lab | purpose == purpose3.lab) %>% 
  mutate(sampling = ifelse(purpose == purpose1.lab, "Indiscriminate sampling", "Targeted sampling"))

p1 <- ggplot(data = p1.240.df, 
             aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = sampling, fill = sampling, shape = sampling), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = sampling, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("A) Percent in HPDI") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme(legend.title = element_blank()) + 
  facet_wrap(~parameter)

samps <- 240
p2.240.df <- results.all %>% dplyr::filter(parameter == "Nm" | parameter == "surv" | parameter == "Nf", total_samples == samps, purpose == purpose1.lab | purpose == purpose3.lab) %>% 
  mutate(sampling = ifelse(purpose == purpose1.lab, "Indiscriminate sampling", "Targeted sampling"))

p2 <- p2.240.df %>% ggplot(aes(x = relative_bias, color = sampling, fill = sampling)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = paste0("B) Relative bias of posterior median")) + 
  xlim(-75, 75) + 
  facet_wrap(~parameter) +
  theme(legend.title = element_blank())



#Nm & surv - 960 samples
#random (non-targeted) sampling: all comps and downsample
p3.960.df <- all.960.4viz %>% filter(parameter == "Nm" | parameter == "surv" | parameter == "Nf") %>% 
  dplyr::filter(purpose == purpose1.lab | purpose == purpose2.lab) %>% 
  mutate(comparisons = ifelse(purpose == purpose1.lab, "All comparisons", "Downsample"))

p3 <- ggplot(data =  p3.960.df,
             aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = comparisons, fill = comparisons, shape = comparisons), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = comparisons, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 2) + 
  ggtitle("A) Indiscriminate sampling") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme(legend.title = element_blank(), 
        axis.title.x = element_blank()) + 
  facet_wrap(~parameter)

#Targeted sampling: all comps and downsample
p4.960.df <- all.960.4viz %>% filter(parameter == "Nm" | parameter == "surv" | parameter == "Nf") %>% 
  dplyr::filter(purpose == purpose3.lab | purpose == purpose4.lab) %>% 
  mutate(comparisons = ifelse(purpose == purpose3.lab, "All comparisons", "Downsample"))

p4 <- ggplot(data = p4.960.df, 
                  aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = comparisons, fill = comparisons, shape = comparisons), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = comparisons, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 2) + 
  ggtitle("B) Targeted sampling") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme(legend.title = element_blank(), 
        axis.title.x = element_blank()) + 
  facet_wrap(~parameter)


#960 samples, indiscriminate sampling
samps <- 960
p5.960.df <- results.all %>% dplyr::filter(parameter == "Nm" | parameter == "surv" | parameter == "Nf", total_samples == samps, purpose == purpose1.lab | purpose == purpose2.lab) %>% 
  mutate(comparisons = ifelse(purpose == purpose1.lab, "All comparisons", "Downsample"))

p5 <- p5.960.df %>% ggplot(aes(x = relative_bias, color = comparisons, fill = comparisons)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = paste0("C) Indiscriminate sampling")) + 
  xlim(-50, 50) + 
  facet_wrap(~parameter) +
  theme(legend.title = element_blank())

#960 samples, targeted sampling
p6.960.df <- results.all %>% dplyr::filter(parameter == "Nm" | parameter == "surv" | parameter == "Nf", total_samples == samps, purpose == purpose3.lab | purpose == purpose4.lab) %>% 
  mutate(comparisons = ifelse(purpose == purpose3.lab, "All comparisons", "Downsample"))

p6 <- p6.960.df %>% ggplot(aes(x = relative_bias, color = comparisons, fill = comparisons)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = paste0("D) Targeted sampling")) + 
  xlim(-50, 50) + 
  facet_wrap(~parameter) +
  theme(legend.title = element_blank())


ggarrange(p1, p2, common.legend = TRUE, ncol = 1, nrow = 2) #Random sampling across age classes does better when few samples are taken
ggarrange(p3, p4, common.legend = TRUE, ncol = 1, nrow = 2) #Targeted sampling of specific age classes performs better when sampling heavily.
ggarrange(p5, p6, common.legend = TRUE, ncol = 1, nrow = 2, legend = "bottom")
```

```{r Figure 3}
####---------------------Density plots of kin detected----------------------------------------------####
#---------------------Prepare data for plotting----------------------------------------------#
#How many POPs detected per sample size?
results.all %>% 
  group_by(purpose2, total_samples) %>% 
  summarize(mean(POPs_detected), mean(HSPs_detected))

#Format PO dataframe
results.PO <- results.all %>% dplyr::select(parameter, total_samples, kin.detected = POPs_detected,  unique_parents_in_sample, iteration, cv, purpose = purpose2) %>% 
  mutate(type = "PO")

#Format HS dataframe
results.HS <- results.all %>% dplyr::select(parameter, total_samples, kin.detected = HSPs_detected,  unique_parents_in_sample, iteration, cv, purpose = purpose2) %>% 
  mutate(type = "HS")

#Combine PO and HS dataframe for plotting
results.kin <- rbind(results.PO, results.HS) %>% 
  mutate(total_samples = paste0(total_samples, " samples"))

results.kin$total_samples <- factor(results.kin$total_samples, levels = c("200 samples", "600 samples", "1000 samples"))
results.kin$purpose <- factor(results.kin$purpose, levels = c("Down sampled", "All samples"))

#---------------------Create density plots----------------------------------------------#
#Maternal
k1 <- results.kin %>% dplyr::filter(parameter == "Nf", type == "PO") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "MOPs detected") + 
  xlim(0, 60) + 
  facet_wrap(~total_samples, ncol = 1) + 
  theme(legend.title = element_blank())

k2 <- results.kin %>% dplyr::filter(parameter == "Nf", type == "HS") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "Maternal HSPs detected") + 
  xlim(0, 500) + 
  facet_wrap(~total_samples, ncol = 1) + 
  theme(legend.title = element_blank())

m.kin <- ggarrange(k1, k2, ncol = 2, common.legend = TRUE)
annotate_figure(m.kin, fig.lab = "Mother kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")



#Paternal
k3 <- results.kin %>% dplyr::filter(parameter == "Nm", type == "PO") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "FOPs detected") + 
  xlim(0, 60) + 
  facet_wrap(~total_samples, ncol = 1) + 
  theme(legend.title = element_blank())

k4 <- results.kin %>% dplyr::filter(parameter == "Nm", type == "HS") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "FHSPs detected") + 
  xlim(0, 500) + 
  facet_wrap(~total_samples, ncol = 1)

f.kin <- ggarrange(k3, k4, ncol = 2, common.legend = TRUE)
annotate_figure(f.kin, fig.lab = "Father kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")

#---------------------Create pdf of kin pair density plots----------------------------------------------#
#Specify file
KinPairs.file <- paste0(results_plots_location, "Distribution_of_kin_", today, "_", purpose.combo, ".pdf")
pdf(file = KinPairs.file, width = 11, height = 14) #Open pdf

annotate_figure(m.kin, fig.lab = "Mother kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")
annotate_figure(f.kin, fig.lab = "Father kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")

dev.off() #close pdf





#-----------------------Examine expected vs observed kin pairs--------------------
#Make better labels for plotting
results.all$sample.label <- factor(paste0(results.all$total_samples, " samples"), levels = c("200 samples", "600 samples", "1000 samples"))

#Calcualte % difference in expected vs observed kin
results.all2 <- results.all %>% mutate(HS_exp_obs_diff = (Exp_HSPs - HSPs_detected)/Exp_HSPs,
                                      PO_exp_obs_diff = (Exp_POPs - POPs_detected)/Exp_POPs) %>%
  mutate(PO_exp_obs_diff = replace_na(PO_exp_obs_diff, 0)) %>% 
  mutate(all_exp_obs_diff = HS_exp_obs_diff + PO_exp_obs_diff)


# results.all %>% mutate(HS_exp_obs_diff = Exp_HSPs - HSPs_detected,
#                        PO_exp_obs_diff = Exp_POPs - POPs_detected) %>%
#   mutate(all_exp_obs_diff = HS_exp_obs_diff + PO_exp_obs_diff) %>% 
#   dplyr::select(purpose,
#                 parameter, 
#                 Q50, 
#                 truth, 
#                 Exp_POPs, 
#                 POPs_detected, 
#                 PO_exp_obs_diff, 
#                 Exp_HSPs, 
#                 HSPs_detected, 
#                 HS_exp_obs_diff, 
#                 total_samples, 
#                 relative_bias, 
#                 in_interval) %>% 
#   View()

#----------------Make scatter plot of expected vs observed 
#Purpose 1
EO1 <- results.all2 %>% dplyr::filter(purpose.lab == purpose1.lab) %>% 
  ggplot(aes(x = all_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~sample.label) + 
  labs(title = purpose1.lab, x = "Percent difference", y = "Relative bias") + 
  theme(legend.title = element_blank())

#Purpose 2
EO2 <- results.all2 %>% dplyr::filter(purpose.lab == purpose2.lab) %>% 
  ggplot(aes(x = all_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~sample.label) + 
  labs(title = purpose2.lab, x = "Percent difference", y = "Relative bias")

#Purpose 3
EO3 <- results.all2 %>% dplyr::filter(purpose.lab == purpose3.lab) %>% 
  ggplot(aes(x = all_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~sample.label) + 
  labs(title = purpose3.lab, x = "Percent difference", y = "Relative bias")

#Purpose 4
EO4 <- results.all2 %>% dplyr::filter(purpose.lab == purpose4.lab) %>% 
  ggplot(aes(x = all_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~sample.label) + 
  labs(title = purpose4.lab, x = "Percent difference", y = "Relative bias")


EO.all <- ggarrange(EO1, EO2, EO3, EO4, common.legend = TRUE)
annotate_figure(EO.all, fig.lab = "Relative bias by percent difference in expected vs observed kin pairs", fig.lab.pos = "top.left", fig.lab.size = 14, fig.lab.face = "bold")
```