---
title: "Data_analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#devtools::install_github("pconn/HierarchicalGOF/HierarchicalGOF")
#install.packages("ggmcmc")
```

```{r read-in-files, include=FALSE}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(coda)
library(runjags)
library(ggmcmc)
library(viridis)

rm(list=ls())
today <- format(Sys.Date(), "%d%b%Y")
purpose.combo <- "test new equation from Liz" #What am I comparing right now? This will be used to name output files


#----------------Read in files ------------------------------
#------------- MCMC parameters ----------------#
ni <- 40000 # number of post-burn-in samples per chain
nb <- 50000 # number of burn-in samples
nt <- 20     # thinning rate
nc <- 2      # number of chains
MCMC.settings <- paste0("thin", nt, "_draw", ni, "_burn", nb)

#Initialize values
purpose1.lab = purpose2.lab = purpose3.lab = purpose4.lab <- NULL

#------------- Simulation parameters and labels  ----------------#
date.of.simulation1 <- "06Jun2022"
purpose1 <- "psi1_0.05non.conform_target.YOY_no.downsample_UpdatedEquation"
purpose1.lab <- "Target YOY"
model.type1 <- "HS.only"

date.of.simulation2 <- "06Jun2022"
purpose2 <- "psi1_0.05non.conform_all.ages.sampled_no.downsample_UpdatedEquation"
purpose2.lab <- "All ages sampled"
model.type2 <- "HS.only"

date.of.simulation3 <- "07Jun2022"
purpose3 <- "psi1_0.05non.conform_all.ages.sampled_yes.downsample_UpdatedEquation"
purpose3.lab <- "All ages sampled + downsample"
model.type3 <- "HS.only"

date.of.simulation4 <- "16May2022"
purpose4 <- "psi1_0.05non.conform_all.ages.sampled_yes.downsample_informative.priors"
purpose4.lab <- "All ages sampled | informed priors"
model.type4 <- "HS.only"

seeds <- "Seeds2022.04.15"
sim.samples.1 <- "0.5prop.sampled" #Label on file output
samples1.lab <- "0.5 percent sampled" #Label for dataframe and figures
sim.samples.2 <- "1prop.sampled" #Label on file output
samples2.lab <- "1 percent sampled" #Label for dataframe and figures
sim.samples.3 <- "1.5prop.sampled"  #Label on file output
samples3.lab <- "1.5 percent sampled" #Label for dataframe and figures
sim.samples.4 <- "2prop.sampled" #Label on file output
samples4.lab <- "2 percent sampled" #Label for dataframe and figures
sim.samples.all <- c(0.5, 1, 1.5, 2) #This is the number of samples when sampling specific proportions of the juvenile population for the HS only model. Current as of 05/03/2022

sim.samples.labs.all <- c(samples1.lab, samples2.lab, samples3.lab, samples4.lab)

MCMC_location <- "G://My Drive/Personal_Drive/R/CKMR/Objective.1_model.construction/Model.output/"
results_location <- "G://My Drive/Personal_Drive/R/CKMR/Objective.1_model.construction/Model.results/"
results_plots_location <- "G://My Drive/Personal_Drive/R/CKMR/Objective.1_model.construction/Model.results/figures/"
results_prefix <- "CKMR_results"
MCMC_prefix <- "CKMR_modelout"
parents_prefix <- "parents_breakdown/CKMR_parents.breakdown"
sample.prefix <- "sample_info/CKMR_sample.info"
survival.prefix <- "survival/CKMR_survival"
pop.size.prefix <- "pop_size/CKMR_pop.size"
mom.comps.prefix <- "comparisons/mom.comps"
dad.comps.prefix <- "comparisons/dad.comps"


#Set results to NULL and the script will run regardless of how many actual results are being compared
results.1 = results.2 = results.3 = results.4 <- NULL

results.1 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1, ".csv")) %>% 
  mutate(model_type = model.type1, 
         purpose.lab = purpose1.lab) %>% 
  mutate(total_samples = total_juvenile_samples + total_adult_samples)

results.2 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2, ".csv")) %>% 
  mutate(model_type = model.type2,
         purpose.lab = purpose2.lab) %>% 
    mutate(total_samples = total_juvenile_samples + total_adult_samples)


results.3 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3, ".csv")) %>% 
  mutate(model_type = model.type3,
         purpose.lab = purpose3.lab) %>% 
      mutate(total_samples = total_juvenile_samples + total_adult_samples)

results.4 <- read_csv(paste0(results_location, results_prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4, ".csv")) %>% 
    mutate(model_type = model.type4,
           purpose.lab = purpose4.lab) %>% 
      mutate(total_samples = total_juvenile_samples + total_adult_samples)
#------------------------------- MCMC output -----------------------------------#
#date.of.simulation <- "07Apr2022"
#Trial 1
s1.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose1))

s1.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose1))

s1.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose1))

s1.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation1, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose1))

#Trial 2
s2.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose2))

s2.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose2))

s2.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose2))

s2.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation2, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose2))

#Trial 3
#date.of.simulation <- "05Apr2022"
s3.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose3))

s3.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose3))

s3.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose3))

s3.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation3, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose3))

#Trial 4
 s4.1 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.1, "_", MCMC.settings, "_", purpose4))

 s4.2 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.2, "_", MCMC.settings, "_", purpose4))

 s4.3 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.3, "_", MCMC.settings, "_", purpose4))
 
  s4.4 <- readRDS(paste0(MCMC_location, MCMC_prefix, "_", date.of.simulation4, "_", seeds, "_", sim.samples.4, "_", MCMC.settings, "_", purpose4))

#------------------------------- Population size details -----------------------------------#
#date.of.simulation <- "07Apr2022"
pop.size.1 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1))

pop.size.2 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2))

pop.size.3 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3))

pop.size.4 <- readRDS(paste0(results_location, pop.size.prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4))

#------------------------------ Pairwise comparison matrices -------------------------------#
#Mom
mom.comps.1 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1))

mom.comps.2 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2))

mom.comps.3 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3))

mom.comps.4 <- readRDS(paste0(results_location, mom.comps.prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4))

#Dad
dad.comps.1 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation1, "_", seeds, "_", purpose1))

dad.comps.2 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation2, "_", seeds, "_", purpose2))

dad.comps.3 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation3, "_", seeds, "_", purpose3))

dad.comps.4 <- readRDS(paste0(results_location, dad.comps.prefix, "_", date.of.simulation4, "_", seeds, "_", purpose4))

```

```{r Quick analysis of results}
####------------------------------- Quick analysis of results -----------------------------------####

results.all <- results.1 %>% 
  bind_rows(results.2, results.3, results.4) %>% 
     mutate(relative_bias = round(((Q50 - all.truth)/all.truth)*100, 1)) %>% #Can change truth to breed.truth if looking for number of active breeders
     mutate(in_interval = ifelse(HPD2.5 < all.truth & all.truth < HPD97.5, "Y", "N")) %>% 
  mutate(cv = (sd/mean)*100) %>% 
  mutate(samples.lab = paste0(prop_sampled_juvs, " percent sampled")) %>% 
  separate(col = purpose.lab, into = "sampling.scheme", sep = " -", remove = FALSE)

results.all$samples.lab <- factor(results.all$samples.lab, levels = c(samples1.lab, samples2.lab, samples3.lab, samples4.lab))
results.all %>% dplyr::filter(is.na(samples.lab == TRUE)) #Should not be any

results.all$purpose.lab <- factor(results.all$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))
results.all %>% dplyr::filter(is.na(purpose.lab == TRUE)) #Should not be any
#Specify parameters
#jags_params <- c("Nfa", "Nfb", "Nm", "surv", "lam", "psi", "pb") #if estimating all parameters with the HS|PO model
jags_params <- c("Nfb", "psi", "Nm", "surv", "lam") #If estimating all parameters with the HS only model

head(results.all)


#View instances where the model failed to converge
results.all %>% dplyr::filter(Rhat > 1.01) %>% nrow()

#Save instances that failed to converge so they can be removed later from the HPDI dataframes
no.convergence <- results.all %>% dplyr::filter(Rhat > 1.01) %>% 
  mutate(purp = ifelse(purpose.lab == purpose1.lab, 1,
                       ifelse(purpose.lab == purpose2.lab, 2,
                              ifelse(purpose.lab == purpose3.lab, 3, 4)))) %>% 
  mutate(samps = ifelse(total_samples == sim.samples.all[1], 1,
                        ifelse(total_samples == sim.samples.all[2], 2,
                               ifelse(total_samples == sim.samples.all[3], 3, 4)))) %>% 
  distinct(purpose.lab, purp, total_samples, iteration, samps)

#Remove instances that failed to converge
results.all <- results.all %>% dplyr::filter(Rhat < 1.01)

 #-----------Median Relative bias by sample size-------------------------#
results.all %>% group_by(prop_sampled_juvs, parameter, purpose.lab) %>% 
#  dplyr::filter(model_type == "HS.PO") %>%
  dplyr::summarize(median = median(relative_bias)) %>% 
  arrange(desc(median)) %>%
#  dplyr::filter(parameter == "psi") %>% 
  View()

# results2 %>% dplyr::filter(parameter == "lam") %>% 
#   ggplot(aes(relative_bias, colour = which.dup, fill = which.dup)) +
#   geom_density(alpha = 0.5)
# 
# 
# results2 %>%  mutate(cv = (sd/mean)*100) %>% 
#   group_by(parameter, which.dup) %>% 
#   dplyr::summarize(mean.cv = mean(cv), mean.relative.bias = mean(relative_bias)) %>%
# #  dplyr::filter(parameter == "Nf" | parameter == "Nm") %>% 
#   arrange(mean.cv) %>% 
#   write_csv(file = paste0(results_location, "Mean_bias_and_precision_", date.of.simulation, "_", purpose, ".csv"))


#------------------------------- Within HPDI? -----------------------------------#
results.all %>% group_by(purpose.lab, prop_sampled_juvs, parameter) %>% 
  dplyr::summarize(percent_in_interval = sum(in_interval == "Y")/n() * 100) %>% 
#  filter(parameter != "lam") %>% 
  arrange(desc(percent_in_interval)) %>% 
  #dplyr::filter(parameter == "psi") %>% 
  View()

results.all %>% dplyr::filter(parameter == "psi", samples.lab != samples1.lab) %>% 
  View()

#------------------------------- CV -----------------------------------#
results.all %>% group_by(model_type, purpose.lab, total_samples, parameter) %>% 
  dplyr::summarize(mean.cv = mean(cv), 
                   median.bias = median(relative_bias),
                   percent_in_interval = sum(in_interval == "Y")/n() * 100) %>%
#  dplyr::filter(parameter == "Nf" | parameter == "Nm") %>% 
  arrange(mean.cv) %>% 
#  write_csv(file = paste0(results_location, "bias_and_precision/Mean_bias_and_precision_", today, "_", purpose.combo, ".csv"))


#-----------------------------Numbers of Kin pairs---------------------#
results.all %>% dplyr::filter(parameter == "Nfb" | parameter == "Nm") %>% 
  group_by(purpose.lab, parameter, prop_sampled_juvs) %>% 
  summarize(mean.HSPs = mean(HSPs_detected),
            mean.POPs = mean(POPs_detected)) %>%
  View()


```

```{r Calcualte HPDI intervals}
####------------------------------- Calculate different HPDI intervals-------------------------------#### 
#How many estimates fall in different HPD intervals?
#Calculate HPD interval for each iteration
intervals <- c(seq(from = 0.95, to = 0.05, by = -0.05)) #Specify HPDI intervals to calculate
iterations = 100

#Assumes four "purposes" are being compared
#Initialize dataframes for loop below
HPD.samples1.1 <- NULL
HPD.samples2.1 <- NULL
HPD.samples3.1 <- NULL
HPD.samples4.1 <- NULL
HPD.samples1.2 <- NULL
HPD.samples2.2 <- NULL
HPD.samples3.2 <- NULL
HPD.samples4.2 <- NULL
HPD.samples1.3 <- NULL
HPD.samples2.3 <- NULL
HPD.samples3.3 <- NULL
HPD.samples4.3 <- NULL
HPD.samples1.4 <- NULL
HPD.samples2.4 <- NULL
HPD.samples3.4 <- NULL
HPD.samples4.4 <- NULL


#Check lists for null and remove
#length(s3.4[-which(sapply(s3.1, is.null))])
#s3.1 <- s3.1[-which(sapply(s3.1, is.null))]

#Assumes all scenarios have the same number of saved iterations; if not, then can just run a separate for loop
for(i in 1:length(s1.1)){ #Loop over all the posterior samples from each iteration; length should be same as number of iterations
  for(j in 1:length(intervals)){ #Loop over the different intervals for calculating HPDI
    
    #---------------------------Purpose 1--------------------------------#
    #samples1 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples1.1 <- combine.mcmc(s1.1[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples1.1 <- post.HPD.samples1.1[row.names(post.HPD.samples1.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples1.1 <- rbind(HPD.samples1.1, post.HPD.samples1.1)
    
    #samples2 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples2.1 <- combine.mcmc(s1.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples2.1 <- post.HPD.samples2.1[row.names(post.HPD.samples2.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.samples2.1 <- rbind(HPD.samples2.1, post.HPD.samples2.1)
    
     #samples3 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples3.1 <- combine.mcmc(s1.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples3.1 <- post.HPD.samples3.1[row.names(post.HPD.samples3.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.samples3.1 <- rbind(HPD.samples3.1, post.HPD.samples3.1)

    #samples4 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples4.1 <- combine.mcmc(s1.3[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples4.1 <- post.HPD.samples4.1[row.names(post.HPD.samples4.1) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.samples4.1 <- rbind(HPD.samples4.1, post.HPD.samples4.1)
    
    
    #---------------------------Purpose 2--------------------------------#    
    #samples1 samples
    #Calcualte HPD interval for iteration i and interval j
    
    post.HPD.samples1.2 <- combine.mcmc(s2.1[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples1.2 <- post.HPD.samples1.2[row.names(post.HPD.samples1.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.samples1.2 <- rbind(HPD.samples1.2, post.HPD.samples1.2)
    
    #samples2 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples2.2 <- combine.mcmc(s2.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples2.2 <- post.HPD.samples2.2[row.names(post.HPD.samples2.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.samples2.2 <- rbind(HPD.samples2.2, post.HPD.samples2.2)
    
        #samples3 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples3.2 <- combine.mcmc(s2.2[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples3.2 <- post.HPD.samples3.2[row.names(post.HPD.samples3.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.samples3.2 <- rbind(HPD.samples3.2, post.HPD.samples3.2)
    
    #samples4 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples4.2 <- combine.mcmc(s2.3[[i]]) %>% 
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>% 
      mutate(interval = intervals[j], iteration = i)
    
    post.HPD.samples4.2 <- post.HPD.samples4.2[row.names(post.HPD.samples4.2) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")
    
    HPD.samples4.2 <- rbind(HPD.samples4.2, post.HPD.samples4.2)
  }    
     print(paste0("Finished with iteration ", i))
  }

  
for(i in 1:length(s3.1)){ #Loop over all the posterior samples from each iteration; length should be same as number of iterations
  for(j in 1:length(intervals)){ #Loop over the different intervals for calculating HPDI

   # #---------------------------Purpose 3--------------------------------#
    #samples1 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples1.3 <- combine.mcmc(s3.1[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples1.3 <- post.HPD.samples1.3[row.names(post.HPD.samples1.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples1.3 <- rbind(HPD.samples1.3, post.HPD.samples1.3)
    

    #samples2 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples2.3 <- combine.mcmc(s3.2[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples2.3 <- post.HPD.samples2.3[row.names(post.HPD.samples2.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples2.3 <- rbind(HPD.samples2.3, post.HPD.samples2.3)

        #samples3 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples3.3 <- combine.mcmc(s3.2[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples3.3 <- post.HPD.samples3.3[row.names(post.HPD.samples3.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples3.3 <- rbind(HPD.samples3.3, post.HPD.samples3.3)

    #samples4 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples4.3 <- combine.mcmc(s3.3[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples4.3 <- post.HPD.samples4.3[row.names(post.HPD.samples4.3) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples4.3 <- rbind(HPD.samples4.3, post.HPD.samples4.3)
   }
   print(paste0("Finished with iteration ", i))
   }

    #---------------------------Purpose 4--------------------------------#
    #samples1 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples1.4 <- combine.mcmc(s4.1[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples1.4 <- post.HPD.samples1.4[row.names(post.HPD.samples1.4) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples1.4 <- rbind(HPD.samples1.4, post.HPD.samples1.4)

    #samples2 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples2.4 <- combine.mcmc(s4.2[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples2.4 <- post.HPD.samples2.4[row.names(post.HPD.samples2.4) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples2.4 <- rbind(HPD.samples2.4, post.HPD.samples2.4)

        #samples3 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples3.4 <- combine.mcmc(s4.2[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples3.4 <- post.HPD.samples3.4[row.names(post.HPD.samples3.4) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples3.4 <- rbind(HPD.samples3.4, post.HPD.samples3.4)

    #samples4 samples
    #Calcualte HPD interval for iteration i and interval j
    post.HPD.samples4.4 <- combine.mcmc(s4.3[[i]]) %>%
      HPDinterval(prob = intervals[j]) %>%
      data.frame() %>%
      mutate(interval = intervals[j], iteration = i)

    post.HPD.samples4.4 <- post.HPD.samples4.4[row.names(post.HPD.samples4.4) %in% jags_params,] %>% #Remove deviance
      rownames_to_column(var = "parameter")

    HPD.samples4.4 <- rbind(HPD.samples4.4, post.HPD.samples4.4)

   # }
   # print(paste0("Finished with iteration ", i))
   # }
```

```{r Create dataframes for HPDI plots}
####------------------------------- Create dataframes for HPDI plotting------------------------------#### 

#---------------------------Purpose 1 --------------------------------#    
#Separate out by sample size
HPD.samples1.1.4viz <- results.1 %>% filter(prop_sampled_juvs == sim.samples.all[1]) %>% 
  right_join(HPD.samples1.1, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples1.lab)
  
HPD.samples2.1.4viz <- results.1 %>% filter(prop_sampled_juvs == sim.samples.all[2]) %>% 
  right_join(HPD.samples2.1, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples2.lab)

HPD.samples3.1.4viz <- results.1 %>% dplyr::filter(prop_sampled_juvs == sim.samples.all[3]) %>% 
  right_join(HPD.samples3.1, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples3.lab)

HPD.samples4.1.4viz <- results.1 %>% filter(prop_sampled_juvs == sim.samples.all[4]) %>% 
  right_join(HPD.samples4.1, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples4.lab)


#Calculate percent estimates in each interval
HPD.samples1.1.summary <- HPD.samples1.1.4viz %>% group_by(parameter, interval) %>% 
#  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.0.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples2.1.summary <- HPD.samples2.1.4viz %>% group_by(parameter, interval) %>% 
#  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>%#If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
    dplyr::summarize(percent_in_interval.1_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples3.1.summary <- HPD.samples3.1.4viz %>% group_by(parameter, interval) %>% 
#  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.1.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPDsamples4.1.summary <- HPD.samples4.1.4viz %>% group_by(parameter, interval) %>%
  #mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.2_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes    
HPD.1.summary_all <- HPD.samples1.1.summary %>% inner_join(HPD.samples2.1.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD.samples3.1.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPDsamples4.1.summary, by = c("parameter", "interval")) %>% 
  mutate(interval.scale = interval*100)

#Read in previously saved file
#HPD.1.summary_all <- read_csv(file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation1, "_", purpose1, ".csv"))

HPD.1.summary.tidy <- HPD.1.summary_all %>% 
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "proportion_sampled",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
    ) %>% 
  mutate(model_type = model.type1,
         purpose.lab = purpose1.lab)

#Save
#write_csv(HPD.1.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation1, "_", purpose1, ".csv"))


#---------------------------Purpose 2 --------------------------------#    
#Separate out by sample size
HPD.samples1.2.4viz <- results.2 %>% filter(prop_sampled_juvs == sim.samples.all[1]) %>% 
  right_join(HPD.samples1.2, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples1.lab)

HPD.samples2.2.4viz <- results.2 %>% filter(prop_sampled_juvs == sim.samples.all[2]) %>% 
  right_join(HPD.samples2.2, by = c("parameter", "iteration")) %>% 
    anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples2.lab)

HPD.samples3.2.4viz <- results.2 %>% filter(prop_sampled_juvs == sim.samples.all[3]) %>% 
  right_join(HPD.samples3.2, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples3.lab)


HPD.samples4.2.4viz <- results.2 %>% filter(prop_sampled_juvs == sim.samples.all[4]) %>% 
  right_join(HPD.samples4.2, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples4.lab)


#Calculate percent estimates in each interval
HPD.samples1.2.summary <- HPD.samples1.2.4viz %>% group_by(parameter, interval) %>% 
#  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.0.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples2.2.summary <- HPD.samples2.2.4viz %>% group_by(parameter, interval) %>% 
#  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.1_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples3.2.summary <- HPD.samples3.2.4viz %>% group_by(parameter, interval) %>% 
#  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.1.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPDsamples4.2.summary <- HPD.samples4.2.4viz %>% group_by(parameter, interval) %>%
  #mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.2_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes
HPD.2.summary_all <- HPD.samples1.2.summary %>% inner_join(HPD.samples2.2.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD.samples3.2.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPDsamples4.2.summary, by = c("parameter", "interval")) %>% 
  mutate(interval.scale = interval*100)

#Read in previously saved file
#HPD.2.summary_all <- read_csv(file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation2, "_", purpose2, ".csv"))

HPD.2.summary.tidy <- HPD.2.summary_all %>% 
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "proportion_sampled",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
  ) %>% 
  mutate(model_type = model.type2,
                  purpose.lab = purpose2.lab)

#Save
#write_csv(HPD.2.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation2, "_", purpose2, ".csv"))


#---------------------------Purpose 3 --------------------------------# 
#Separate out by sample size
HPD.samples1.3.4viz <- results.3 %>% filter(prop_sampled_juvs == sim.samples.all[1]) %>% 
  right_join(HPD.samples1.3, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples1.lab)


HPD.samples2.3.4viz <- results.3 %>% filter(prop_sampled_juvs == sim.samples.all[2]) %>% 
  right_join(HPD.samples2.3, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples2.lab)


HPD.samples3.3.4viz <- results.3 %>% filter(prop_sampled_juvs == sim.samples.all[3]) %>% 
  right_join(HPD.samples3.3, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples3.lab)


HPD.samples4.3.4viz <- results.3 %>% filter(prop_sampled_juvs == sim.samples.all[4]) %>% 
  right_join(HPD.samples4.3, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples4.lab)


#Calculate percent estimates in each interval
HPD.samples1.3.summary <- HPD.samples1.3.4viz %>% group_by(parameter, interval) %>% 
#  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.0.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples2.3.summary <- HPD.samples2.3.4viz %>% group_by(parameter, interval) %>% 
  # mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.1_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples3.3.summary <- HPD.samples3.3.4viz %>% group_by(parameter, interval) %>% 
  # mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth
  dplyr::summarize(percent_in_interval.1.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPDsamples4.3.summary <- HPD.samples4.3.4viz %>% group_by(parameter, interval) %>%
  # mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% #If using breed truth for females
  mutate(in_HPD_interval = ifelse(lower < all.truth & all.truth < upper, "Y", "N")) %>% #If using all truth  
  dplyr::summarize(percent_in_interval.2_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes
HPD.3.summary_all <- HPD.samples1.3.summary %>% inner_join(HPD.samples2.3.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPD.samples3.3.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPDsamples4.3.summary, by = c("parameter", "interval")) %>% 
  mutate(interval.scale = interval*100)

#Read in previously saved file
#HPD.3.summary_all <- read_csv(file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation3, "_", purpose3, ".csv"))

HPD.3.summary.tidy <- HPD.3.summary_all %>% 
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "proportion_sampled",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
  ) %>% 
  mutate(model_type = model.type3,
         purpose.lab = purpose3.lab)

#Save
#write_csv(HPD.3.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation3, "_", purpose3, ".csv"))


#---------------------------Purpose 4 --------------------------------# 
#Separate out by sample size
HPD.samples1.4.4viz <- results.4 %>% filter(prop_sampled_juvs == sim.samples.all[1]) %>%
  right_join(HPD.samples1.4, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples1.lab)


HPD.samples2.4.4viz <- results.4 %>% filter(prop_sampled_juvs == sim.samples.all[2]) %>%
  right_join(HPD.samples2.4, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples2.lab)


HPD.samples3.4.4viz <- results.4 %>% filter(prop_sampled_juvs == sim.samples.all[3]) %>%
  right_join(HPD.samples3.4, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples3.lab)


HPD.samples4.4.4viz <- results.4 %>% filter(prop_sampled_juvs == sim.samples.all[4]) %>%
  right_join(HPD.samples4.4, by = c("parameter", "iteration")) %>% 
  anti_join(no.convergence, by = c("purpose.lab", "iteration", "total_samples")) %>%  #Remove iterations that failed to converge
  mutate(samples.lab = samples4.lab)



#Calculate percent estimates in each interval
HPD.samples1.4.summary <- HPD.samples1.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% 
  dplyr::summarize(percent_in_interval.0.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples2.4.summary <- HPD.samples2.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% 
  dplyr::summarize(percent_in_interval.1_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPD.samples3.4.summary <- HPD.samples3.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% 
  dplyr::summarize(percent_in_interval.1.5_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

HPDsamples4.4.summary <- HPD.samples4.4.4viz %>% group_by(parameter, interval) %>%
  mutate(in_HPD_interval = ifelse(parameter == "Nfb", ifelse(lower < breed.truth & breed.truth < upper, "Y", "N"), ifelse(lower < all.truth & all.truth < upper, "Y", "N"))) %>% 
  dplyr::summarize(percent_in_interval.2_percent_sampled = sum(in_HPD_interval == "Y")/n() * 100)

#Combine above dataframes
HPD.4.summary_all <- HPD.samples1.4.summary %>% inner_join(HPD.samples2.4.summary, by = c("parameter", "interval")) %>%
  inner_join(HPD.samples3.4.summary, by = c("parameter", "interval")) %>% 
  inner_join(HPDsamples4.4.summary, by = c("parameter", "interval")) %>%
  mutate(interval.scale = interval*100)

#Read in previously saved file
#HPD.4.summary_all <- read_csv(file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation4, "_", purpose4, ".csv"))

HPD.4.summary.tidy <- HPD.4.summary_all %>%
  pivot_longer(
    cols = starts_with("percent"),
    names_to = "proportion_sampled",
    names_prefix = "percent_in_interval.",
    values_to = "percent_in_interval"
  ) %>%
  mutate(model_type = model.type4,
         purpose.lab = purpose4.lab)

#Save
#write_csv(HPD.4.summary_all, file = paste0(results_location, "HPD.summaries/HPD.summary_", date.of.simulation4, "_", purpose4, ".csv"))


#---------------Create dataframes to plot by sample size--------#
#Set eveyrthing to Null so the below scripts will run
HPD.samples1.1.4viz = HPD.samples2.1.4viz = HPD.samples3.1.4viz = HPD.samples4.1.4viz = HPD.samples1.2.4viz = HPD.samples2.2.4viz = HPD.samples3.2.4viz = HPD.samples4.2.4viz = HPD.samples1.3.4viz = HPD.samples2.3.4viz = HPD.samples3.3.4viz = HPD.samples4.3.4viz = HPD.samples1.4.4viz = HPD.samples2.4.4viz = HPD.samples3.4.4viz = HPD.samples4.4.4viz <- NULL

HPD.samples1.1.4viz <- HPD.1.summary.tidy %>% filter(proportion_sampled == "0.5_percent_sampled")
HPD.samples2.1.4viz <- HPD.1.summary.tidy %>% filter(proportion_sampled == "1_percent_sampled")
HPD.samples3.1.4viz <- HPD.1.summary.tidy %>% filter(proportion_sampled == "1.5_percent_sampled")
HPD.samples4.1.4viz <- HPD.1.summary.tidy %>% filter(proportion_sampled == "2_percent_sampled")

HPD.samples1.2.4viz <- HPD.2.summary.tidy %>% filter(proportion_sampled == "0.5_percent_sampled")
HPD.samples2.2.4viz <- HPD.2.summary.tidy %>% filter(proportion_sampled == "1_percent_sampled")
HPD.samples3.2.4viz <- HPD.2.summary.tidy %>% filter(proportion_sampled == "1.5_percent_sampled")
HPD.samples4.2.4viz <- HPD.2.summary.tidy %>% filter(proportion_sampled == "2_percent_sampled")

HPD.samples1.3.4viz <- HPD.3.summary.tidy %>% filter(proportion_sampled == "0.5_percent_sampled")
HPD.samples2.3.4viz <- HPD.3.summary.tidy %>% filter(proportion_sampled == "1_percent_sampled")
HPD.samples3.3.4viz <- HPD.3.summary.tidy %>% filter(proportion_sampled == "1.5_percent_sampled")
HPD.samples4.3.4viz <- HPD.3.summary.tidy %>% filter(proportion_sampled == "2_percent_sampled")

HPD.samples1.4.4viz <- HPD.4.summary.tidy %>% filter(proportion_sampled == "0.5_percent_sampled")
HPD.samples2.4.4viz <- HPD.4.summary.tidy %>% filter(proportion_sampled == "1_percent_sampled")
HPD.samples3.4.4viz <- HPD.4.summary.tidy %>% filter(proportion_sampled == "1.5_percent_sampled")
HPD.samples4.4.4viz <- HPD.4.summary.tidy %>% filter(proportion_sampled == "2_percent_sampled")


#Combine above dataframes, and re-order purpose as factors
all.samples1.4viz <- HPD.samples1.1.4viz %>% bind_rows(HPD.samples1.2.4viz, HPD.samples1.3.4viz, HPD.samples1.4.4viz) 
all.samples1.4viz$purpose.lab <- factor(all.samples1.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

all.samples2.4viz <- HPD.samples2.1.4viz %>% bind_rows(HPD.samples2.2.4viz, HPD.samples2.3.4viz, HPD.samples2.4.4viz) 
all.samples2.4viz$purpose.lab <- factor(all.samples2.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

all.samples3.4viz <- HPD.samples3.1.4viz %>% bind_rows(HPD.samples3.2.4viz, HPD.samples3.3.4viz, HPD.samples3.4.4viz) 
all.samples3.4viz$purpose.lab <- factor(all.samples3.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

all.samples4.4viz <- HPD.samples4.1.4viz %>% bind_rows(HPD.samples4.2.4viz, HPD.samples4.3.4viz, HPD.samples4.4.4viz)
all.samples4.4viz$purpose.lab <- factor(all.samples4.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))

#For when we need everything together
all.4viz <- HPD.1.summary.tidy %>% bind_rows(HPD.2.summary.tidy, HPD.3.summary.tidy, HPD.4.summary.tidy)
all.4viz$purpose.lab <- factor(all.4viz$purpose.lab, levels = c(purpose1.lab, purpose2.lab, purpose3.lab, purpose4.lab))
```

```{r HPDI line graphs}
(p.Nfb <- all.4viz %>% dplyr::filter(parameter == "Nfb") %>% 
   ggplot(aes(x = interval.scale)) +
   geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
   geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
   geom_line(aes(y = interval.scale), size = 1.5) + 
   ggtitle("A) Nf") + 
   labs(x = "HPDI",
        y = "Percent in HPDI") +
   theme_bw() + 
   theme(legend.title = element_blank()) + 
   scale_colour_brewer(palette = "Set1") +
   facet_wrap(~proportion_sampled) + 
  guides(color = guide_legend(nrow = 2)))


(p.Nm <- all.4viz %>% dplyr::filter(parameter == "Nm") %>% 
  ggplot(aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("B) Nm") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~proportion_sampled))


(p.surv <- all.4viz %>% dplyr::filter(parameter == "surv") %>% 
  ggplot(aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("A) Survival") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~proportion_sampled) +
  guides(color = guide_legend(nrow = 2)))


(p.lam <- all.4viz %>% dplyr::filter(parameter == "lam") %>% 
  ggplot(aes(x = interval.scale)) +
  geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
  geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
  geom_line(aes(y = interval.scale), size = 1.5) + 
  ggtitle("Lambda") + 
  labs(x = "HPDI",
       y = "Percent in HPDI") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~proportion_sampled))


(p.psi <- all.4viz %>% dplyr::filter(parameter == "psi") %>% 
    ggplot(aes(x = interval.scale)) +
    geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
    geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
    geom_line(aes(y = interval.scale), size = 1.5) + 
    ggtitle("Percent biennial breeders (psi)") + 
    labs(x = "HPDI",
         y = "Percent in HPDI") +
    theme_bw() + 
    theme(legend.title = element_blank()) + 
    scale_colour_brewer(palette = "Set1") +
    facet_wrap(~proportion_sampled))



#Total adult females
# (p.Nfa <- all.4viz %>% dplyr::filter(parameter == "Nfa") %>% 
#     ggplot(aes(x = interval.scale)) +
#     geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
#     geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
#     geom_line(aes(y = interval.scale), size = 1.5) + 
#     ggtitle("Nf - total") + 
#     labs(x = "HPDI",
#          y = "Percent in HPDI") +
#     theme_bw() + 
#     theme(legend.title = element_blank()) + 
#     scale_colour_brewer(palette = "Set1") +
#     facet_wrap(~samples))
# 
# 
# #Percent breeders
# (p.pb <- all.4viz %>% dplyr::filter(parameter == "pb") %>% 
#     ggplot(aes(x = interval.scale)) +
#     geom_point(aes(y = percent_in_interval, color = purpose.lab, fill = purpose.lab, shape = purpose.lab), size = 2.5, alpha = .7) + 
#     geom_smooth(aes(y = percent_in_interval, color = purpose.lab, linetype = ), se = FALSE, size = 1.5, show.legend = FALSE) + 
#     geom_line(aes(y = interval.scale), size = 1.5) + 
#     ggtitle("Percent breeders") + 
#     labs(x = "HPDI",
#          y = "Percent in HPDI") +
#     theme_bw() + 
#     theme(legend.title = element_blank()) + 
#     scale_colour_brewer(palette = "Set1") +
#     facet_wrap(~samples))


#HPDI.plots.N <- ggarrange(p.Nfb, p.Nm, common.legend = TRUE, legend = "right")
#Save plots so I can load them quickly later
HPDI.plot.list <- list(p.Nfb, p.psi, p.Nm, p.surv, p.lam)
#Save the plots as a list, so I can load them later and plot with ggarrange/annotate_figure
saveRDS(HPDI.plot.list, file = paste0(results_plots_location, "plot_lists/", purpose.combo, "_HPDI_line_plots"))
```

```{r Density plots}
#Density plots
(p2.Nfb <- results.all %>% dplyr::filter(parameter == "Nfb") %>% 
    ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
    ggtitle("C) Nf") + 
    labs(x = "Relative bias of posterior median") +
    geom_vline(xintercept=c(0), linetype="dotted") +
    theme_bw() + 
    theme(legend.title = element_blank()) + 
    scale_fill_brewer(palette = "Set1") +
    xlim(-100, 100) + 
    facet_wrap(~samples.lab))

(p2.Nm <- results.all %>% dplyr::filter(parameter == "Nm") %>% 
  ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
  geom_density(alpha = 0.6) + 
  ggtitle("D) Nm") + 
  labs(x = "Relative bias of posterior median") +
  geom_vline(xintercept=c(0), linetype="dotted") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Set1") +
  xlim(-100, 100) + 
  facet_wrap(~samples.lab))

(p2.surv <- results.all %>% dplyr::filter(parameter == "surv") %>% 
  ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
  geom_density(alpha = 0.6) + 
  ggtitle("B) Survival") + 
  labs(x = "Relative bias of posterior median") +
  geom_vline(xintercept=c(0), linetype="dotted") +
  theme_bw() + 
  theme(legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Set1") +
  xlim(-25, 25) + 
  facet_wrap(~samples.lab))


(p2.psi <- results.all %>% dplyr::filter(parameter == "psi") %>% 
    ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
    ggtitle("Percent biennial breeders (psi)") + 
    labs(x = "Relative bias of posterior median") +
    geom_vline(xintercept=c(0), linetype="dotted") +
    theme_bw() + 
    theme(legend.title = element_blank()) + 
    scale_fill_brewer(palette = "Set1") +
    xlim(-100, 100) + 
    facet_wrap(~samples.lab))


(p2.lam <- results.all %>% dplyr::filter(parameter == "lam") %>% 
    ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
    ggtitle("Lambda") + 
    labs(x = "Relative bias of posterior median") +
    geom_vline(xintercept=c(0), linetype="dotted") +
    theme_bw() + 
    theme(legend.title = element_blank()) + 
    scale_fill_brewer(palette = "Set1") +
    xlim(-10, 10) + 
    facet_wrap(~samples.lab))



# (p2.Nfa <- results.all %>% dplyr::filter(parameter == "Nfa") %>% 
#     ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
#     geom_density(alpha = 0.6) + 
#     ggtitle("Nf - total") + 
#     labs(x = "Relative bias of posterior median") +
#     geom_vline(xintercept=c(0), linetype="dotted") +
#     theme_bw() + 
#     theme(legend.title = element_blank()) + 
#     scale_fill_brewer(palette = "Set1") +
#     xlim(-100, 100) + 
#     facet_wrap(~samples.lab))
# 
# 
# (p2.pb <- results.all %>% dplyr::filter(parameter == "pb") %>% 
#     ggplot(aes(x = relative_bias, color = purpose.lab, fill = purpose.lab)) +
#     geom_density(alpha = 0.6) + 
#     ggtitle("Percent breeders") + 
#     labs(x = "Relative bias of posterior median") +
#     geom_vline(xintercept=c(0), linetype="dotted") +
#     theme_bw() + 
#     theme(legend.title = element_blank()) + 
#     scale_fill_brewer(palette = "Set1") +
#     xlim(-100, 100) + 
#     facet_wrap(~samples.lab))

RelBias.Density.Plots.N <- ggarrange(p2.Nfb, p2.Nm, common.legend = TRUE, legend = "none")
#Save plots so I can load them quickly later
Density.plot.list <- list(p2.Nfb, p2.psi, p2.Nm, p2.surv, p2.lam)
#Save the plots as a list, so I can load them later and plot with ggarrange/annotate_figure
saveRDS(Density.plot.list, file = paste0(results_plots_location, "plot_lists/", purpose.combo, "_Relative_bias_density_plots"))
```

```{r print figures}
#Male and female HPDI and relative bias for low and high sample sizes
ggarrange(p.Nfb, p.Nm, p2.Nfb, p2.Nm, common.legend = TRUE, nrow = 2, ncol = 2, legend = "bottom")

#Survival HPDI and relative bias for all four sample sizes
ggarrange(p.surv, p2.surv, common.legend = TRUE, nrow = 2, legend = "bottom")

#annotate_figure(p = HPDI.plots.N, fig.lab = "A)", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")
```


```{r Plot-kin-pairs, echo=FALSE}
####---------------------Density plots of kin detected----------------------------------------------####

###ADD POPs to each graph
(Nfb_HSPs <- results.all %>% dplyr::filter(parameter == "Nfb",
                                           purpose.lab == purpose1.lab | purpose.lab == purpose3.lab) %>% 
  ggplot(aes(x = HSPs_detected, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
    ggtitle("Maternal HSPs detected") + 
    labs(x = "HSPs") +
    theme_bw() + 
    theme(legend.title = element_blank()) + 
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~samples.lab)) + 
  scale_x_continuous(breaks = c(25, 50, 100, 150, 200, 250))


(Nm_HSPs <- results.all %>% dplyr::filter(parameter == "Nm",
                                          purpose.lab == purpose1.lab | purpose.lab == purpose3.lab) %>% 
  ggplot(aes(x = HSPs_detected, color = purpose.lab, fill = purpose.lab)) +
    geom_density(alpha = 0.6) + 
    ggtitle("Paternal HSPs detected") + 
    labs(x = "HSPs") +
    theme_bw() + 
    theme(legend.title = element_blank()) + 
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~samples.lab)) + 
    scale_x_continuous(breaks = c(25, 50, 100, 150, 200, 250))


#---------------------Prepare data for plotting----------------------------------------------#
#Format PO dataframe
results.PO <- results.all %>% dplyr::select(parameter, total_samples, kin.detected = POPs_detected,  unique_parents_in_sample, iteration, cv, purpose = purpose2) %>% 
  mutate(type = "PO")

#Format HS dataframe
results.HS <- results.all %>% dplyr::select(parameter, total_samples, kin.detected = HSPs_detected,  unique_parents_in_sample, iteration, cv, purpose = purpose2) %>% 
  mutate(type = "HS")

#Combine PO and HS dataframe for plotting
results.kin <- rbind(results.PO, results.HS) %>% 
  mutate(total_samples = paste0(total_samples, " samples"))

results.kin$total_samples <- factor(results.kin$total_samples, levels = c("200 samples", "600 samples", "1000 samples"))
results.kin$purpose <- factor(results.kin$purpose, levels = c("Down sampled", "All samples"))

#---------------------Create density plots----------------------------------------------#
#Maternal
k1 <- results.kin %>% dplyr::filter(parameter == "Nf", type == "PO") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "MOPs detected") + 
  xlim(0, 60) + 
  facet_wrap(~total_samples, ncol = 1) + 
  theme(legend.title = element_blank())

k2 <- results.kin %>% dplyr::filter(parameter == "Nf", type == "HS") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "Maternal HSPs detected") + 
  xlim(0, 500) + 
  facet_wrap(~total_samples, ncol = 1) + 
  theme(legend.title = element_blank())

m.kin <- ggarrange(k1, k2, ncol = 2, common.legend = TRUE)
annotate_figure(m.kin, fig.lab = "Mother kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")



#Paternal
k3 <- results.kin %>% dplyr::filter(parameter == "Nm", type == "PO") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "FOPs detected") + 
  xlim(0, 60) + 
  facet_wrap(~total_samples, ncol = 1) + 
  theme(legend.title = element_blank())

k4 <- results.kin %>% dplyr::filter(parameter == "Nm", type == "HS") %>%
  ggplot(aes(x = kin.detected, color = purpose, fill = purpose)) + 
  geom_density(alpha = 0.6) + 
  ggtitle(label = "FHSPs detected") + 
  xlim(0, 500) + 
  facet_wrap(~total_samples, ncol = 1)

f.kin <- ggarrange(k3, k4, ncol = 2, common.legend = TRUE)
annotate_figure(f.kin, fig.lab = "Father kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")

#---------------------Create pdf of kin pair density plots----------------------------------------------#
#Specify file
KinPairs.file <- paste0(results_plots_location, "Distribution_of_kin_", today, "_", purpose.combo, ".pdf")
pdf(file = KinPairs.file, width = 11, height = 14) #Open pdf

annotate_figure(m.kin, fig.lab = "Mother kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")
annotate_figure(f.kin, fig.lab = "Father kin pairs", fig.lab.pos = "top.left", fig.lab.size = 18, fig.lab.face = "bold")

dev.off() #close pdf





#-----------------------Examine expected vs observed kin pairs--------------------
#Make better labels for plotting
results.all$sample.label <- factor(paste0(results.all$total_samples, " samples"), levels = c("200 samples", "600 samples", "1000 samples"))

#Calcualte % difference in expected vs observed kin
results.all2 <- results.all %>% mutate(HS_exp_obs_diff = (Exp_HSPs - HSPs_detected)/Exp_HSPs,
                                      PO_exp_obs_diff = (Exp_POPs - POPs_detected)/Exp_POPs) %>%
  mutate(PO_exp_obs_diff = replace_na(PO_exp_obs_diff, 0)) %>% 
  mutate(all_exp_obs_diff = HS_exp_obs_diff + PO_exp_obs_diff)


# results.all %>% mutate(HS_exp_obs_diff = Exp_HSPs - HSPs_detected,
#                        PO_exp_obs_diff = Exp_POPs - POPs_detected) %>%
#   mutate(all_exp_obs_diff = HS_exp_obs_diff + PO_exp_obs_diff) %>% 
#   dplyr::select(purpose,
#                 parameter, 
#                 Q50, 
#                 truth, 
#                 Exp_POPs, 
#                 POPs_detected, 
#                 PO_exp_obs_diff, 
#                 Exp_HSPs, 
#                 HSPs_detected, 
#                 HS_exp_obs_diff, 
#                 total_samples, 
#                 relative_bias, 
#                 in_interval) %>% 
#   View()

#----------------Make scatter plot of expected vs observed 
#Purpose 1
(EO1 <- results.all2 %>% dplyr::filter(purpose.lab == purpose1.lab,
                                       parameter == "Nfb" | parameter == "Nm") %>% 
  ggplot(aes(x = HS_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~samples.lab) + 
  labs(title = purpose1.lab, x = "Percent difference", y = "Relative bias") + 
  theme(legend.title = element_blank()))

#Purpose 2
(EO2 <- results.all2 %>% dplyr::filter(purpose.lab == purpose2.lab,
                                       parameter == "Nfb" | parameter == "Nm") %>% 
  ggplot(aes(x = all_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~samples.lab) + 
  labs(title = purpose2.lab, x = "Percent difference", y = "Relative bias"))

#Purpose 3
(EO3 <- results.all2 %>% dplyr::filter(purpose.lab == purpose3.lab,
                                        parameter == "Nfb" | parameter == "Nm") %>% 
  ggplot(aes(x = all_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~samples.lab) + 
  labs(x = "Percent difference", y = "Relative bias"))

#Purpose 4
(EO4 <- results.all2 %>% dplyr::filter(purpose.lab == purpose4.lab,
                                        parameter == "Nfb" | parameter == "Nm") %>% 
  ggplot(aes(x = all_exp_obs_diff, y = relative_bias, fill = parameter, color = parameter)) +
  geom_point() +
  facet_wrap(~samples.lab) + 
  labs(title = purpose4.lab, x = "Percent difference", y = "Relative bias"))


(EO.all <- ggarrange(EO1, EO2, EO3, EO4, common.legend = TRUE, legend = "bottom"))
annotate_figure(EO.all, fig.lab = "Relative bias by percent difference in expected vs observed kin pairs", fig.lab.pos = "top.left", fig.lab.size = 14, fig.lab.face = "bold")
```

```{r troubleshooting results}
results.1.troubleshoot <- results.all %>% dplyr::filter(purpose.lab == purpose1.lab,
                              in_interval == "N") %>% 
  mutate(direction = ifelse(HPD2.5 > truth, "high", "low")) 

results.1.troubleshoot %>%
  group_by(parameter, direction) %>% 
  summarize(n())

ts.iterations <- results.1.troubleshoot %>% group_by(iteration) %>% 
  summarize(num = n()) %>% 
  dplyr::filter(num > 1) %>% 
  pull(iteration)
  



results.1.ts <- results.all %>% dplyr::filter(purpose.lab == purpose1.lab,
                                              iteration %in% ts.iterations) %>% 
    mutate(HPDI.direction = ifelse(HPD2.5 > truth, "high",
                                   ifelse(HPD97.5 < truth, "low", "in.interval"))) %>% 
    mutate(bias.direction = ifelse(relative_bias < 0, "low",
                                   ifelse(relative_bias > 0, "high", "perfect")))

#Isolate iterations that are especially wonky  
results.1.ts %>% group_by(iteration, HPDI.direction) %>% 
  summarize(number = n()) %>% 
  dplyr::filter(HPDI.direction != "in.interval",
                number > 5)


results.1.ts %>% dplyr::filter(iteration == 88 | iteration == 173) %>% 
  View()

mom.comps.1

results.1.ts %>% dplyr::filter(parameter == "Nfb") %>% 
  summarize(mean(Q50))

results.1.ts %>% dplyr::filter(parameter == "psi") %>% 
  summarize(mean(Q50))


testing <- results2 %>% dplyr::filter(total_juvenile_samples == 570 | total_juvenile_samples == 632, parameter == "Nfb" | parameter == "psi" | parameter == "surv" | parameter == "Nm")

testing %>% dplyr::arrange(iteration, parameter) %>% 
  dplyr::select(parameter,
                Q2.5,
                Q50,
                Q97.5,
                sd,
                HPD2.5,
                mean,
                HPD97.5,
                truth,
                Exp_HSPs,
                HSPs_detected,
                prop_sampled_juvs,
                iteration,
                relative_bias,
                pop) %>%
  View()

dad_comps <- readRDS("~/R/working_directory/temp_results/comparisons/dad.comps_04May2022_Seeds2022.04.15_Troubleshoot")

mom_comps <- readRDS("~/R/working_directory/temp_results/comparisons/mom.comps_04May2022_Seeds2022.04.15_Troubleshoot")


dad_comps %>% group_by(iteration, mort.yrs, pop.growth.yrs) %>%
  summarize(total.yes = sum(yes), total.all = sum(all)) %>% 
  summarize(sum.yes = sum(total.yes), sum.all = sum(total.all)) %>% 
  mutate(percent.yes= (sum.yes/sum.all)*100)


mom_comps %>% group_by(iteration, mort.yrs, pop.growth.yrs) %>%
  summarize(total.yes = sum(yes), total.all = sum(all)) %>% 
  summarize(sum.yes = sum(total.yes), sum.all = sum(total.all)) %>% 
  mutate(percent.yes= (sum.yes/sum.all)*100)
```